# Generated by Django 4.0.2 on 2022-02-13 14:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('source', models.CharField(choices=[('Punjab', 'Punjab'), ('Gujrat', 'Gujrat'), ('Mumbai', 'Mumbai'), ('Karnataka', 'Karnataka')], max_length=50)),
                ('destination', models.CharField(choices=[('Punjab', 'Punjab'), ('Gujrat', 'Gujrat'), ('Mumbai', 'Mumbai'), ('Karnataka', 'Karnataka')], max_length=50)),
                ('booking_date', models.CharField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
