# Generated by Django 4.0.2 on 2022-02-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
