# Generated by Django 4.0.2 on 2022-02-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ticket_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discount_price', models.IntegerField()),
                ('actual_price', models.IntegerField()),
                ('descriptions', models.TextField(max_length=300)),
                ('offer_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
