# Generated by Django 4.0.2 on 2022-02-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('addr1', models.CharField(max_length=400)),
                ('addr2', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Punjab', 'Punjab'), ('Gujrat', 'Gujrat'), ('Mumbai', 'Mumbai'), ('Karnataka', 'Karnataka')], max_length=50)),
                ('zipcode', models.IntegerField()),
            ],
        ),
    ]
