# Generated by Django 4.0.2 on 2022-03-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
    ]
